[package]
name = "bitvm_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin-script = { path = "../rust-bitcoin-script" }
bitcoin = "0.31.1"
strum = "0.26"
strum_macros = "0.26"
